name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2025]
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install Poetry
        run: |
          python3 -m pip install --user pipx
          pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Dump environment details
        shell: bash
        run: |
          echo "OS/Runner: ${{ runner.os }}"
          echo "Python version:"
          python --version
          echo "Poetry version:"
          poetry --version
          echo "Poetry Environment Info:"
          poetry env info
          echo "PATH:"
          echo $PATH

      - name: Install dependencies
        run: poetry install --no-interaction -vv

      - name: Verify Dependency Tree
        run: poetry show --tree

      - name: Run Unit Tests
        run: poetry run pytest -vv -m "not integration" tests/ --cov=./ --cov-report=xml:coverage-unit.xml

      - name: Run Integration Tests
        run: poetry run pytest -vv -m "integration" tests/ --cov=./ --cov-report=xml:coverage-integration.xml

      - name: Upload Unit Test coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-unit.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}-unit
          fail_ci_if_error: true
          verbose: true

      - name: Upload Integration Test coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-integration.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}-integration
          fail_ci_if_error: true
          verbose: true

      - name: Upload reports and logs on failure
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: failure()
        with:
          name: ci-failure-reports-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            coverage-unit.xml
            coverage-integration.xml